spring:
  # JPA ??
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: '1000'
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      database: mysql
      ddl-auto: update  # create
    show-sql: 'true'
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pofect?characterEncoding=UTF-8&serverTimezone=UTC
    username: pofect
    password: pofect1!
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://pofect-database.c4jotwudvoiz.ap-northeast-2.rds.amazonaws.com:3306/pofect?characterEncoding=UTF-8&serverTimezone=UTC
#    username: pofect
#    password: 2wh1234!!


# ??
server:
  port: '8080'
  servlet:
    context-path: /api