spring:
  # JPA ??
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: '1000'
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      database: mysql
      ddl-auto: create-drop
    show-sql: 'true'
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pofect?characterEncoding=UTF-8&serverTimezone=UTC
    username: pofect
    password: pofect1!
#  datasource:
#    password: kkotbada15!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: flowerbada_dev
#    url: jdbc:mysql://k7a405.p.ssafy.io:3306/flower_db?characterEncoding=UTF-8&serverTimezone=UTC