spring:
  application:
    name: service-pofect
  profiles:
    active: development
---
spring:
  config:
    activate:
      on-profile: production
    import: optional:configserver:http://localhost:7777

jasypt:
  key: Pofect!LeeCS123Qtkdlek
  encryptor:
    bean: jasyptStringEncryptor

mail:
  password: ENC(+lH9+DRrN5lDGem1GGaT18z0BIJcB1Qfpiio96m4+MA=)
---
spring:
  config:
    activate:
      on-profile: production
    import: optional:configserver:https://config.pofect.store

jasypt:
  key: Pofect!LeeCS123Qtkdlek
  encryptor:
    bean: jasyptStringEncryptor

mail:
  password: ENC(+lH9+DRrN5lDGem1GGaT18z0BIJcB1Qfpiio96m4+MA=)
